databaseChangeLog:

  - changeSet:
      id: users-table
      author: abdoul
      changes:
        - createTable:
            tableName: users
            columns:
              - column:
                  name: id
                  type: varchar(36)
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: username
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: email
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: password
                  type: VARCHAR(255)
                  constraints:
                    nullable: false

  - changeSet:
      id: roles-table
      author: abdoul
      changes:
        - createTable:
            tableName: roles
            columns:
              - column:
                  name: id
                  type: varchar(36)
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
                    unique: true

  - changeSet:
      id: permissions-table
      author: abdoul
      changes:
        - createTable:
            tableName: permissions
            columns:
              - column:
                  name: id
                  type: varchar(36)
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(100)
                  constraints:
                    nullable: false
                    unique: true

  - changeSet:
      id: user-roles-table
      author: abdoul
      changes:
        - createTable:
            tableName: user_roles
            columns:
              - column:
                  name: user_id
                  type: varchar(36)
                  constraints:
                    nullable: false
              - column:
                  name: role_id
                  type: varchar(36)
                  constraints:
                    nullable: false
        - addPrimaryKey:
            tableName: user_roles
            columnNames: user_id, role_id
            constraintName: pk_user_roles
        - addForeignKeyConstraint:
            baseTableName: user_roles
            baseColumnNames: user_id
            referencedTableName: users
            referencedColumnNames: id
            constraintName: fk_user_roles_user
            onDelete: CASCADE
        - addForeignKeyConstraint:
            baseTableName: user_roles
            baseColumnNames: role_id
            referencedTableName: roles
            referencedColumnNames: id
            constraintName: fk_user_roles_role
            yonDelete: CASCADE
        - createIndex:
                tableName: user_roles
                indexName: idx_user_roles_user
                columns:
                  - column:
                      name: user_id


  - changeSet:
      id: role-permissions-table
      author: abdoul
      changes:
        - createTable:
            tableName: role_permissions
            columns:
              - column:
                  name: role_id
                  type: varchar(36)
                  constraints:
                    nullable: false
              - column:
                  name: permission_id
                  type: varchar(36)
                  constraints:
                    nullable: false
        - addPrimaryKey:
            tableName: role_permissions
            columnNames: role_id, permission_id
            constraintName: pk_role_permissions
        - addForeignKeyConstraint:
            baseTableName: role_permissions
            baseColumnNames: role_id
            referencedTableName: roles
            referencedColumnNames: id
            constraintName: fk_role_permissions_role
            onDelete: CASCADE
        - addForeignKeyConstraint:
            baseTableName: role_permissions
            baseColumnNames: permission_id
            referencedTableName: permissions
            referencedColumnNames: id
            constraintName: fk_role_permissions_permission
            onDelete: CASCADE
        - createIndex:
              tableName: role_permissions
              indexName: idx_role_permissions_role
              columns:
                - column:
                      name: role_id