spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/ecomdb
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none

  #liquibase:
    #enabled: false
    #change-log: classpath:db/changelog/db.changelog-master.yaml

